# Generated by Django 4.1.1 on 2022-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
