# Generated by Django 4.1.1 on 2022-09-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_id_post__id_rename_owner_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_total',
        ),
    ]
