# Generated by Django 4.1.1 on 2022-09-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_post_image_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='id',
            new_name='_id',
        ),
    ]
