# Generated by Django 4.1.1 on 2022-09-19 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_id_review__id_rename_id_tag__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
